#This could be usefull to reserve a node
#get-resources:
#  stage: .pre
#  script:
#    - echo "Getting node"
#    - srun --immediate --pty --qos c1_inter_giga --time 1:00:00 --ntasks 8 bash
#    - echo "Now running on $HOSTNAME"

# Prevent duplicated pipeline by removing MR pipelines
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

variables:
  GIT_STRATEGY: none # don't do anything by default
#Common to both stages
before_script:
  - module purge
  - source /home/sonics/spack_new/spack/share/spack/setup-env.sh
  - source /home/sonics/source-intel-oneapi-2021.2-spiro.me --compiler gcc10.1

stages:
  - init
  - build
  - test
  - deploy
#  - report
#  - clean

job:init:
  stage: init
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: none
  before_script: 
    - ''
  script: # explicitly load modules one by one, so that if one fails, it will be easy to identify
    - git submodule update --init external/project_utils
    - git submodule update --init external/cpp_cgns
    - git submodule update --init external/std_e
    - git submodule update --init external/pytest-mpi-check
    - git submodule update --init external/paradigm
    - (cd external/paradigm && git submodule update --init extensions/paradigma)

job:build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -Dmaia_ENABLE_TESTS=ON -Dmaia_ENABLE_COVERAGE=ON -DPDM_ENABLE_EXTENSION_PDMA=ON ../
    - make -j8

# This build documentation after main build, only if branch is dev or for MR events
job:doc:
  stage: build
  needs: ["job:build"]
  rules:
    - if: $CI_OPEN_MERGE_REQUESTS || $CI_COMMIT_BRANCH == "dev"
  script:
    - cd build
    - source source.sh
    - cmake -Dmaia_ENABLE_DOCUMENTATION=ON .
    - make maia_sphinx


#todo : display reports on browser eg with gitlab pages
job:unitary:
  stage: test
  script:
    - cd build
    - ctest -E pdm
  after_script:
    - cd build/test
    - coverage combine --rcfile=.coveragerc_unit_tests
    - coverage report --rcfile=.coveragerc_unit_tests
    - coverage xml --rcfile=.coveragerc_unit_tests -o coverage_unit_tests.xml
    - sed 's@'"$CI_PROJECT_DIR"'/@@' -i coverage_unit_tests.xml
  when: on_success # s'exécutera uniquement si le job `job:build` passe
  artifacts:
    paths:
      - ./build/test/reports/*
    when: always
    # Next allows to display a test tab in the pipeline with report but requires a feature flag to be enabled,
    # see https://docs.gitlab.com/ee/ci/unit_test_reports.html#viewing-unit-test-reports-on-gitlab
    # Use it in combination with --junitxml=reports/pytest-junit.xml in the pytest launcher (TestCreate.cmake)
    reports:
      junit: ./build/test/reports/*_test.xml
      cobertura: ./build/test/coverage_unit_tests.xml

job:doc_snippets:
  stage: test
  script:
    - cd build
    - source source.sh; unset PYTEST_PLUGINS
    - python3 -m pytest ../doc

# Deploy the documentation sphinx documentation to the site, only if branch is dev
job:deploy_doc:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script: 
    - ''
  script:
    - cd build/doc/sphinx/html
    # I dont know how to clean the repo before (deltree does not work on spiro) so lets erase everything
    - smbclient -U jcoulet%$DROPPY_PSSWD //droopy2/Maia -c "prompt OFF; recurse ON; mput *"


#job:report:
#  stage: report
#  script:
#    - cd build
#    - make report
#  when: on_failure # s'exécutera si le job `job:build` ou `job:test` ne passe pas

#job:clean:
#  stage: clean
#  script:
#    - cd build
#    - make clean # s'exécutera quoi qu'il se passe
#  when: always

